// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCbiwrlmiYMHFGR4hROGplxDcSma_xkQoE',
    appId: '1:1038551703956:web:3dc4d3d072fb3d6ba02f81',
    messagingSenderId: '1038551703956',
    projectId: 'audiodetectauth',
    authDomain: 'audiodetectauth.firebaseapp.com',
    storageBucket: 'audiodetectauth.firebasestorage.app',
    measurementId: 'G-FLG84ZEY96',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDyfdp6u67bebSbMAxIepvME1z4njN2SfY',
    appId: '1:1038551703956:android:aebafa025259c441a02f81',
    messagingSenderId: '1038551703956',
    projectId: 'audiodetectauth',
    storageBucket: 'audiodetectauth.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCx34f_R1MWlPbh3trUKLDKfm-JijrFpI4',
    appId: '1:1038551703956:ios:a603bf69beb914b6a02f81',
    messagingSenderId: '1038551703956',
    projectId: 'audiodetectauth',
    storageBucket: 'audiodetectauth.firebasestorage.app',
    iosBundleId: 'com.example.cyberSheild',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCx34f_R1MWlPbh3trUKLDKfm-JijrFpI4',
    appId: '1:1038551703956:ios:a603bf69beb914b6a02f81',
    messagingSenderId: '1038551703956',
    projectId: 'audiodetectauth',
    storageBucket: 'audiodetectauth.firebasestorage.app',
    iosBundleId: 'com.example.cyberSheild',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCbiwrlmiYMHFGR4hROGplxDcSma_xkQoE',
    appId: '1:1038551703956:web:5aaa06f0175e3af8a02f81',
    messagingSenderId: '1038551703956',
    projectId: 'audiodetectauth',
    authDomain: 'audiodetectauth.firebaseapp.com',
    storageBucket: 'audiodetectauth.firebasestorage.app',
    measurementId: 'G-5RRFEZ9L30',
  );
}
